### ISSUE TITLE
reload-client.js via /reload/reload.js fails when Node server is listening on port 80

### ISSUE THREAD

**Issue by superhawk610** [alallier/reload#126]
In the latest stable build of Chrome, `window.location.origin` doesn't include a port number when the port is 80, thus the regex for setting `socketUrl` in reload-client.js fails to match and produces an error when attempting to open a new WebSocket on the client's side.

I'm sure this isn't a common issue as most Node development is done on ports other than 80, but it sure gave me a headache for 20 minutes.

**Comment by yamboy1** [comment]
What error does it give?

**Comment by superhawk610** [comment]
Here's the error:
![image](https://user-images.githubusercontent.com/18172185/28096808-afa6a7ac-6679-11e7-8152-6bd86b559014.png)

Which leads to this line in the trace:
![image](https://user-images.githubusercontent.com/18172185/28096822-d1cd1eec-6679-11e7-8dba-18bf8fedc9e4.png)

`socketUrl` is set at this line:
![image](https://user-images.githubusercontent.com/18172185/28096900-570677e8-667a-11e7-81e0-0b71f944a867.png)

Logging the value of `window.location.origin` shows that it is `http://localhost`, which would fail to match that regex as it has no colon or port number following. The same thing happens at 127.0.0.1, as `window.location.origin` resolves to `http://127.0.0.1`, again with no colon or port number.

**Comment by alallier** [comment]
Very nice catch. Feel free to send PR otherwise we will get this patched soon

**Comment by meszaros-lajos-gyorgy** [comment]
So what is the temporary solution until the fix is released? Should I run my server on different port?

**Comment by meszaros-lajos-gyorgy** [comment]
Answering to my previous question: Yes, just run the code on port 3000 or something, but not on 80.

**Comment by yamboy1** [comment]
Should I add a note on README.md explaining this? I can remove it when the fix is released.

**Comment by alallier** [comment]
@meszaros-lajos-gyorgy yes for now. I will get the fix up now. @yamboy1 that should answer your question too.

**Comment by alallier** [comment]
@meszaros-lajos-gyorgy should be all set. Publish to npm

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!

**Comment by johhansantana** [comment]
I'm still getting this error.

Running the server on port 3000

```javascript
...

const server = http.createServer(app);

reload(app);

server.listen(3000, () => console.log("Example app listening on port 3000!"));
```

and I have copied the client javascript

```html
<script src="/src/js/reload-client.js" ></script>
```

```
VM746:164 Uncaught DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed.
    at new WrappedWebSocket (<anonymous>:164:21)
    at http://localhost:3000/src/js/reload-client.js:94:16
```

**Comment by alallier** [comment]
@johhansantana you are not including your JS script tag correctly. It should look like this `<script src="/reload/reload.js"></script>`. Reload creates a route and serves the client side file initialized for you. You should not require it directly. Give that tweak a try and refer to the [example](https://github.com/alallier/reload#express-example) and let me know if you still have trouble.
